version: 0.2

phases:
  build:
    commands:
      - cd functions && zip -r textract-lambda-code.zip *
      - aws s3 cp textract-lambda-code.zip s3://esg-textract-code/textract-lambda-code.zip

artifacts:
  files:
    - '**/*'
